/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package as_arvores_somos_nozes_2.Visual;

import as_arvores_somos_nozes_2.GerenciarArvores.ArvereDescadeirada;
import as_arvores_somos_nozes_2.GerenciarArvores.ArvoreB;
import as_arvores_somos_nozes_2.GerenciarArvores.ArvoreCadeirada;
import as_arvores_somos_nozes_2.GerenciarArvores.Flamengo_RubroNegro;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author sergy
 */
public class Tela extends javax.swing.JFrame {
    private ArvereDescadeirada arvoreDesbalanceada = new ArvereDescadeirada();
    private ArvoreCadeirada arvoreCadeirada = new ArvoreCadeirada();
    private Flamengo_RubroNegro flamenguista = new Flamengo_RubroNegro();
    private ArvoreB biruBiru = new ArvoreB(4);
    private Tela instanciaTela;
    public Tela() {
        initComponents();
    }
    
public void ExibirArvoreGraficamente(ArvoreCadeirada arvoreCadeirada, ArvereDescadeirada arvoreDesbalanceada, ArvoreB arvoreB, Flamengo_RubroNegro arvoreRubroNegro) {
    
    this.biruBiru = arvoreB;
    this.arvoreCadeirada = arvoreCadeirada;
    this.arvoreDesbalanceada = arvoreDesbalanceada;
    this.flamenguista = arvoreRubroNegro;
    
    /*
    jTextAreaGraficamenteArvores.setText("Árvore Balanceada (ArvoreCadeirada):\n");
    mostrarArvoreCadeiradaGraficamente(arvoreCadeirada.getRoot(), "");

    jTextAreaGraficamenteArvores.append("\n\nÁrvore Desbalanceada (ArvereDescadeirada):\n");
    mostrarArvoreDescadeiradaGraficamente(arvoreDesbalanceada.getRoot(), "");

    jTextAreaGraficamenteArvores.setText("\n\nÁrvore B:\n");
    mostrarArvoreBgraficamente(arvoreB.getRaiz(), "");

    jTextAreaGraficamenteArvores.setText("\n\nÁrvore Rubro-Negra (Flamengo_RubroNegro):\n");
    mostrarArvoreRNgraficamente(arvoreRubroNegro.getRaiz(), "");
  */
}

private void mostrarArvoreCadeiradaGraficamente(ArvoreCadeirada.Nozinho noAtual, String prefix) {
    if (noAtual != null) {
        jTextAreaGraficamenteArvores.append(prefix + noAtual.data + "\n");
        mostrarArvoreCadeiradaGraficamente(noAtual.left, prefix + "└──: ");
        mostrarArvoreCadeiradaGraficamente(noAtual.right, prefix + "└──: ");
    }
}

private void mostrarArvoreDescadeiradaGraficamente(ArvereDescadeirada.Nozinho noAtual, String prefix) {
    if (noAtual != null) {
        jTextAreaGraficamenteArvores.append(prefix + noAtual.data + "\n");
        mostrarArvoreDescadeiradaGraficamente(noAtual.left, prefix + "└──: ");
        mostrarArvoreDescadeiradaGraficamente(noAtual.right, prefix + "└──: ");
    }
}

private void mostrarArvoreBgraficamente(ArvoreB.NoDaArvoreB noAtual, String prefix) {
    if (noAtual != null) {
        jTextAreaGraficamenteArvores.append(prefix + noAtual.toString() + "\n");
        
        // Itere pelos filhotes do nó atual e chame recursivamente o método.
        for (int i = 0; i < noAtual.filhotes.size(); i++) {
            mostrarArvoreBgraficamente(noAtual.filhotes.get(i), prefix + "└──" + i + ": ");
        }
    }
}


private void mostrarArvoreRNgraficamente(Flamengo_RubroNegro.NodoRN<String, String> noAtual, String prefix) {
    if (noAtual != null) {
        String cor = (noAtual.cor == Flamengo_RubroNegro.VERMELHO) ? " (R)" : " (B)";
        jTextAreaGraficamenteArvores.append(prefix + noAtual.chave + cor + "\n");
        mostrarArvoreRNgraficamente(noAtual.esquerda, prefix + "└──: ");
        mostrarArvoreRNgraficamente(noAtual.direita, prefix + "└──: ");
    }
}


    
public void  printarTextoGraficamente(ArrayList<String> treco){
    for(int c = 0; c < treco.size(); c++){
        jTextAreaTexto.setText(jTextAreaTexto.getText() + treco.get(c));
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaGraficamenteArvores = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTexto = new javax.swing.JTextArea();
        jButtonCadeirada = new javax.swing.JButton();
        jButtonDescadeirada = new javax.swing.JButton();
        jButtonBigBrotherBrasil = new javax.swing.JButton();
        jButtonFlamenguista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaGraficamenteArvores.setColumns(20);
        jTextAreaGraficamenteArvores.setRows(5);
        jTextAreaGraficamenteArvores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(jTextAreaGraficamenteArvores);

        jTextAreaTexto.setColumns(20);
        jTextAreaTexto.setRows(5);
        jTextAreaTexto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(jTextAreaTexto);

        jButtonCadeirada.setText("Balanceada");
        jButtonCadeirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadeiradaActionPerformed(evt);
            }
        });

        jButtonDescadeirada.setText("Desbalanceada");
        jButtonDescadeirada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDescadeiradaActionPerformed(evt);
            }
        });

        jButtonBigBrotherBrasil.setText("B");
        jButtonBigBrotherBrasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBigBrotherBrasilActionPerformed(evt);
            }
        });

        jButtonFlamenguista.setText("RubroNegro");
        jButtonFlamenguista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFlamenguistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadeirada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonDescadeirada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jButtonBigBrotherBrasil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(jButtonFlamenguista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonCadeirada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDescadeirada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBigBrotherBrasil, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonFlamenguista, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadeiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadeiradaActionPerformed
        jTextAreaGraficamenteArvores.setText("Árvore Balanceada (ArvoreCadeirada):\n");
        mostrarArvoreCadeiradaGraficamente(arvoreCadeirada.getRoot(), "");
    }//GEN-LAST:event_jButtonCadeiradaActionPerformed

    private void jButtonDescadeiradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDescadeiradaActionPerformed
    jTextAreaGraficamenteArvores.setText("\n\nÁrvore Desbalanceada (ArvereDescadeirada):\n");
    mostrarArvoreDescadeiradaGraficamente(arvoreDesbalanceada.getRoot(), "");
    }//GEN-LAST:event_jButtonDescadeiradaActionPerformed

    private void jButtonBigBrotherBrasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBigBrotherBrasilActionPerformed
        if (biruBiru.getRaiz() != null) {
            jTextAreaGraficamenteArvores.setText("\n\nÁrvore B:\n");
            mostrarArvoreBgraficamente(biruBiru.getRaiz(), "");
        } else {
            // Trate o caso em que biruBiru.getRaiz() é nulo, por exemplo, exibindo uma mensagem de erro.
            jTextAreaGraficamenteArvores.setText("\n\nÁrvore B está vazia ou não foi inicializada.");
        }
    }//GEN-LAST:event_jButtonBigBrotherBrasilActionPerformed

    private void jButtonFlamenguistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFlamenguistaActionPerformed
    jTextAreaGraficamenteArvores.setText("\n\nÁrvore Rubro-Negra (Flamengo_RubroNegro):\n");
    mostrarArvoreRNgraficamente(flamenguista.getRaiz(), "");
    }//GEN-LAST:event_jButtonFlamenguistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBigBrotherBrasil;
    private javax.swing.JButton jButtonCadeirada;
    private javax.swing.JButton jButtonDescadeirada;
    private javax.swing.JButton jButtonFlamenguista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaGraficamenteArvores;
    private javax.swing.JTextArea jTextAreaTexto;
    // End of variables declaration//GEN-END:variables
}
